# Generated by Django 3.1.1 on 2020-09-03 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('permalink', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('observing', models.BooleanField(verbose_name='rescan and get repoort with cron')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('scan_date', models.DateTimeField(verbose_name='scan date')),
                ('detections', models.IntegerField(verbose_name='# of detections')),
                ('engines', models.IntegerField(verbose_name='# of AV engines')),
                ('json_url', models.CharField(max_length=256, verbose_name='url of got json file')),
                ('status', models.CharField(max_length=3, verbose_name='status code of API')),
                ('sha256', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observes.hash', verbose_name='hash')),
            ],
        ),
    ]
