# Generated by Django 3.1.1 on 2020-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='detections',
            field=models.IntegerField(blank=True, null=True, verbose_name='# of detections'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='engines',
            field=models.IntegerField(blank=True, null=True, verbose_name='# of AV engines'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='json_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='url of got json file'),
        ),
    ]
