# Generated by Django 3.1.1 on 2020-09-03 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observes', '0003_auto_20200903_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
