# Generated by Django 3.1.1 on 2020-09-03 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observes', '0004_auto_20200903_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('status', models.CharField(max_length=3, verbose_name='status code of API')),
                ('sha256', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observes.hash', verbose_name='hash')),
            ],
        ),
    ]
