# Generated by Django 3.1.1 on 2020-09-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observes', '0005_reanalyze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='sha256',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_of_hash', to='observes.hash', verbose_name='hash'),
        ),
        migrations.CreateModel(
            name='AvclassResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_count', models.IntegerField(blank=True, null=True, verbose_name='# of AV engines which detects family level')),
                ('class_count', models.IntegerField(blank=True, null=True, verbose_name='# of AV engines which detects class level')),
                ('beh_count', models.IntegerField(blank=True, null=True, verbose_name='# of AV engines which detects behavior level')),
                ('file_count', models.IntegerField(blank=True, null=True, verbose_name='# of AV engines which detects file level')),
                ('unk_count', models.IntegerField(blank=True, null=True, verbose_name='# of AV engines which detects unknown level')),
                ('result', models.JSONField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avclass_result_of_scan', to='observes.scan', verbose_name='scan')),
                ('sha256', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avclass_results_of_hash', to='observes.hash', verbose_name='hash')),
            ],
        ),
    ]
