# Generated by Django 3.1.4 on 2021-01-04 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observes', '0006_auto_20200928_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawReportEntropies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('engine', models.CharField(max_length=30, verbose_name='AV engine')),
                ('report', models.CharField(max_length=100, verbose_name='raw report')),
                ('entropy', models.FloatField(verbose_name='entropy')),
                ('valuecounts', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
