# Generated by Django 3.1.4 on 2021-01-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observes', '0007_rawreportentropies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avclassresult',
            old_name='class_count',
            new_name='variety_count',
        ),
        migrations.AddField(
            model_name='avclassresult',
            name='beh',
            field=models.CharField(default='nan', max_length=50, verbose_name='max votes for variety'),
        ),
        migrations.AddField(
            model_name='avclassresult',
            name='family',
            field=models.CharField(default='nan', max_length=50, verbose_name='max votes for family'),
        ),
        migrations.AddField(
            model_name='avclassresult',
            name='file',
            field=models.CharField(default='nan', max_length=50, verbose_name='max votes for file'),
        ),
        migrations.AddField(
            model_name='avclassresult',
            name='unk',
            field=models.CharField(default='nan', max_length=50, verbose_name='max votes for unknown'),
        ),
        migrations.AddField(
            model_name='avclassresult',
            name='variety',
            field=models.CharField(default='nan', max_length=50, verbose_name='max votes for class'),
        ),
    ]
